version: '3.8'

services:
  redis:
    image: redis:6.0.9-alpine
    ports:
      - 6379
    volumes:
      - redis-data:/data
  
  db:
    image: postgres:13.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  api:
    build: ./api
    depends_on:
      - redis
      - db
    ports:
      - 8000:8000
  
  web:
    build: ./front/loan-analysis
    depends_on:
      - api
    ports:
      - 80:80
  
volumes:
  redis-data:
  postgres-data: