# Generated by Django 4.2.4 on 2023-08-25 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('email', 'E-mail'), ('phone', 'Telefone'), ('boolean', 'Booleano'), ('select', 'Seleção'), ('file', 'Arquivo'), ('textarea', 'Área de texto')], max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=False, help_text='Indica se o campo estará presente no formulário de empréstimo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('0', 'Em Análise'), ('1', 'Reprovado'), ('2', 'Aprovado')], max_length=1)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
