# Generated by Django 4.2.4 on 2023-08-26 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loan_user_uuid_delete_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
