# Generated by Django 4.2.4 on 2023-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loan_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='avaliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
