# Generated by Django 4.2.4 on 2023-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan_avaliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('0', 'Em Análise'), ('1', 'Pré-Aprovado'), ('2', 'Reprovado'), ('3', 'Aprovado')], max_length=1),
        ),
    ]
