# Generated by Django 4.2.4 on 2023-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('email', 'E-mail'), ('phone', 'Telefone'), ('boolean', 'Booleano'), ('textarea', 'Área de texto')], max_length=255),
        ),
    ]
