# Generated by Django 4.2.4 on 2023-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('email', 'E-mail'), ('phone', 'Telefone'), ('textarea', 'Área de texto')], max_length=255),
        ),
    ]
